# -*- coding: utf-8 -*-
"""лабм3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5r5Bzgj2LELV2hYxl-dlr68lEWLh41-
"""

# ===== Шифрование гаммированием конечной гаммой =====
# Лабораторная работа: реализация алгоритма шифрования конечной гаммой

def text_to_numbers(text: str) -> list:
    """
    Преобразование текста в числовые коды (позиции букв в алфавите)
    """
    # Русский алфавит (33 буквы)
    alphabet = 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'
    numbers = []

    for char in text.upper():
        if char in alphabet:
            # Позиция буквы в алфавите (начиная с 1)
            numbers.append(alphabet.index(char) + 1)
        else:
            # Если символ не найден в алфавите, пропускаем
            print(f"Предупреждение: символ '{char}' не входит в алфавит и будет пропущен")

    return numbers


def numbers_to_text(numbers: list) -> str:
    """
    Преобразование числовых кодов обратно в текст
    """
    alphabet = 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'
    text = ''

    for num in numbers:
        if 1 <= num <= 33:
            text += alphabet[num - 1]
        else:
            text += '?'

    return text


def encrypt(message: str, gamma: str, mod: int = 33) -> tuple:
    """
    Шифрование сообщения с использованием конечной гаммы
    """
    # Преобразуем сообщение и гамму в числовые коды
    message_numbers = text_to_numbers(message)
    gamma_numbers = text_to_numbers(gamma)

    print(f"Исходное сообщение: {message}")
    print(f"Числовые коды сообщения: {message_numbers}")
    print(f"Гамма: {gamma}")
    print(f"Числовые коды гаммы: {gamma_numbers}")
    print()

    # Шифрование: складываем по модулю mod
    encrypted_numbers = []
    gamma_length = len(gamma_numbers)

    for i in range(len(message_numbers)):
        # Берем соответствующий символ гаммы (циклически, если гамма короче сообщения)
        gamma_index = i % gamma_length
        gamma_value = gamma_numbers[gamma_index]

        # Операция сложения по модулю
        encrypted_value = (message_numbers[i] + gamma_value) % mod
        # Если получился 0, заменяем на mod (в нашей нумерации 1..33)
        if encrypted_value == 0:
            encrypted_value = mod

        encrypted_numbers.append(encrypted_value)

    # Преобразуем числа обратно в текст
    encrypted_text = numbers_to_text(encrypted_numbers)

    return encrypted_numbers, encrypted_text


def decrypt(encrypted_numbers: list, gamma: str, mod: int = 33) -> tuple:
    """
    Дешифрование сообщения с использованием конечной гаммы
    """
    gamma_numbers = text_to_numbers(gamma)

    print(f"Зашифрованные числовые коды: {encrypted_numbers}")
    print(f"Гамма: {gamma}")
    print(f"Числовые коды гаммы: {gamma_numbers}")
    print()

    # Дешифрование: вычитаем по модулю mod
    decrypted_numbers = []
    gamma_length = len(gamma_numbers)

    for i in range(len(encrypted_numbers)):
        gamma_index = i % gamma_length
        gamma_value = gamma_numbers[gamma_index]

        # Операция вычитания по модулю
        decrypted_value = (encrypted_numbers[i] - gamma_value) % mod
        # Если получился 0, заменяем на mod
        if decrypted_value == 0:
            decrypted_value = mod

        decrypted_numbers.append(decrypted_value)

    # Преобразуем числа обратно в текст
    decrypted_text = numbers_to_text(decrypted_numbers)

    return decrypted_numbers, decrypted_text


def print_verbose_step(message_num: int, gamma_num: int, result_num: int, step: int):
    """
    Детальный вывод одного шага шифрования/дешифрования
    """
    print(f"  Шаг {step}: {message_num:2d} + {gamma_num:2d} mod 33 = {result_num:2d}")


def encrypt_verbose(message: str, gamma: str, mod: int = 33) -> tuple:
    """
    Шифрование с детальным выводом каждого шага
    """
    message_numbers = text_to_numbers(message)
    gamma_numbers = text_to_numbers(gamma)

    print("=" * 50)
    print("ПРОЦЕСС ШИФРОВАНИЯ")
    print("=" * 50)
    print(f"Исходное сообщение: {message}")
    print(f"Числовые коды сообщения: {message_numbers}")
    print(f"Гамма: {gamma}")
    print(f"Числовые коды гаммы: {gamma_numbers}")
    print("-" * 50)
    print("Вычисление:")

    encrypted_numbers = []
    gamma_length = len(gamma_numbers)

    for i in range(len(message_numbers)):
        gamma_index = i % gamma_length
        gamma_value = gamma_numbers[gamma_index]
        encrypted_value = (message_numbers[i] + gamma_value) % mod

        if encrypted_value == 0:
            encrypted_value = mod

        encrypted_numbers.append(encrypted_value)

        # Детальный вывод
        print_verbose_step(message_numbers[i], gamma_value, encrypted_value, i + 1)

    encrypted_text = numbers_to_text(encrypted_numbers)

    print("-" * 50)
    print(f"Криптограмма (числа): {encrypted_numbers}")
    print(f"Криптограмма (текст): {encrypted_text}")
    print("=" * 50)

    return encrypted_numbers, encrypted_text


def decrypt_verbose(encrypted_numbers: list, gamma: str, mod: int = 33) -> tuple:
    """
    Дешифрование с детальным выводом каждого шага
    """
    gamma_numbers = text_to_numbers(gamma)

    print("=" * 50)
    print("ПРОЦЕСС ДЕШИФРОВАНИЯ")
    print("=" * 50)
    print(f"Криптограмма (числа): {encrypted_numbers}")
    print(f"Гамма: {gamma}")
    print(f"Числовые коды гаммы: {gamma_numbers}")
    print("-" * 50)
    print("Вычисление:")

    decrypted_numbers = []
    gamma_length = len(gamma_numbers)

    for i in range(len(encrypted_numbers)):
        gamma_index = i % gamma_length
        gamma_value = gamma_numbers[gamma_index]

        decrypted_value = (encrypted_numbers[i] - gamma_value) % mod
        if decrypted_value == 0:
            decrypted_value = mod

        decrypted_numbers.append(decrypted_value)

        # Детальный вывод
        print(f"  Шаг {i + 1}: {encrypted_numbers[i]:2d} - {gamma_value:2d} mod 33 = {decrypted_value:2d}")

    decrypted_text = numbers_to_text(decrypted_numbers)

    print("-" * 50)
    print(f"Расшифрованные числа: {decrypted_numbers}")
    print(f"Расшифрованный текст: {decrypted_text}")
    print("=" * 50)

    return decrypted_numbers, decrypted_text


# ===== Тестирование =====
def run_lab_example():
    """
    Выполнение примера из лабораторной работы
    """
    print("=" * 60)
    print("ПРИМЕР ИЗ ЛАБОРАТОРНОЙ РАБОТЫ")
    print("=" * 60)

    message = "ПРИКАЗ"
    gamma = "ГАММА"

    print(f"Исходные данные:")
    print(f"  Сообщение: '{message}'")
    print(f"  Гамма: '{gamma}'")
    print(f"  Модуль: 33")
    print()

    # Шифрование
    encrypted_nums, encrypted_text = encrypt_verbose(message, gamma)

    print()

    # Дешифрование
    decrypted_nums, decrypted_text = decrypt_verbose(encrypted_nums, gamma)

    # Проверка
    print()
    print("ПРОВЕРКА:")
    print(f"  Исходное сообщение: '{message}'")
    print(f"  Расшифрованное:     '{decrypted_text}'")
    print(f"  Результат: {'✓ СОВПАДАЕТ' if message.upper() == decrypted_text else '✗ НЕ СОВПАДАЕТ'}")


def run_additional_tests():
    """
    Дополнительные тесты
    """
    print("\n" + "=" * 60)
    print("ДОПОЛНИТЕЛЬНЫЕ ТЕСТЫ")
    print("=" * 60)

    test_cases = [
        ("КРИПТОГРАФИЯ", "КЛЮЧ"),
        ("АТАКА", "ЩИТ"),
        ("ЗАЩИТА", "ШИФР"),
        ("СООБЩЕНИЕ", "ГАММА")
    ]

    for msg, key in test_cases:
        print(f"\nТест: '{msg}' с гаммой '{key}'")

        # Шифрование
        enc_nums, enc_text = encrypt(msg, key)
        print(f"  Зашифровано: '{enc_text}' ({enc_nums})")

        # Дешифрование
        dec_nums, dec_text = decrypt(enc_nums, key)
        print(f"  Расшифровано: '{dec_text}' ({dec_nums})")

        # Проверка
        if msg.upper() == dec_text:
            print("  ✓ УСПЕШНО")
        else:
            print("  ✗ ОШИБКА")


def interactive_mode():
    """
    Интерактивный режим для ввода своих данных
    """
    print("\n" + "=" * 60)
    print("ИНТЕРАКТИВНЫЙ РЕЖИМ")
    print("=" * 60)

    message = input("Введите сообщение для шифрования: ")
    gamma = input("Введите гамму (ключ): ")

    print("\n" + "-" * 40)
    print("ШИФРОВАНИЕ:")
    enc_nums, enc_text = encrypt_verbose(message, gamma)

    print("\n" + "-" * 40)
    print("ДЕШИФРОВАНИЕ:")
    dec_nums, dec_text = decrypt_verbose(enc_nums, gamma)


# ===== Основная программа =====
if __name__ == "__main__":
    print("=" * 60)
    print("ЛАБОРАТОРНАЯ РАБОТА: ШИФРОВАНИЕ ГАММИРОВАНИЕМ")
    print("=" * 60)
    print()
__
    # Выполнение примера из лабораторной работы
    run_lab_example()

    # Дополнительные тесты
    run_additional_tests()

    # Предложение интерактивного режима
    print("\n" + "=" * 60)
    choice = input("Хотите попробовать свой пример? (да/нет): ")

    if choice.lower() in ['да', 'yes', 'y', 'д']:
        interactive_mode()

    print("\nРабота завершена.")