# -*- coding: utf-8 -*-
"""лабм4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiLKqV8Gkc56WHdkzS1HMfJ8YX_8zkeg
"""

def euclidean_algorithm(a: int, b: int) -> int:
    # Проверка, что b не равно 0
    if b == 0:
        raise ValueError("b не должно быть равно 0")

    # Шаг 1: Инициализация
    r_prev, r_curr = a, b

    # Шаг 2-3: Последовательное деление с остатком
    while True:
        # Находим остаток от деления
        r_next = r_prev % r_curr

        # Если остаток равен 0, возвращаем текущий делитель
        if r_next == 0:
            return abs(r_curr)  # Возвращаем абсолютное значение

        # Обновляем значения для следующей операции
        r_prev, r_curr = r_curr, r_next

# ===== Тестирование алгоритма Евклида =====
test_cases = [
    (48, 18),
    (56, 42),
    (101, 10),
    (17, 19),
    (100, 25),
    (81, 27),
    (144, 89),
    (322, 14),
    (0, 5),        # Тест с нулем (должен вызвать ошибку)
    (-48, 18),     # Тест с отрицательными числами
    (-56, -42)     # Тест с двумя отрицательными числами
]

for a, b in test_cases:
    try:
        gcd_val = euclidean_algorithm(a, b)
        print(f"НОД({a}, {b}) = {gcd_val}")
    except ValueError as e:
        print(f"Ошибка для пары ({a}, {b}): {e}")
print()

# ===== Бинарный алгоритм Евклида =====
def is_even(n: int) -> bool:
    return n % 2 == 0


def binary_euclidean_algorithm(a: int, b: int) -> int:
    # Проверка, что b не равно 0
    if b == 0:
        raise ValueError("b не должно быть равно 0")

    # Шаг 1: Инициализация
    g = 1

    # Шаг 2: Убираем общие множители 2
    while is_even(a) and is_even(b):
        a //= 2
        b //= 2
        g *= 2

    # Шаг 3: Инициализация u и v
    u, v = a, b

    # Шаг 4: Основной цикл
    while u != 0:
        # Убираем множители 2 из u
        while is_even(u):
            u //= 2

        # Убираем множители 2 из v
        while is_even(v):
            v //= 2

        # Шаг 4.3: Вычитание
        if u >= v:
            u = u - v
        else:
            v = v - u

    # Шаг 5: Возвращаем результат
    return g * v


# ===== Бинарный алгоритм Евклида =====
def is_even(n: int) -> bool:
    return n % 2 == 0


def binary_euclidean_algorithm(a: int, b: int) -> int:
    # Prise en compte des valeurs absolues
    a, b = abs(a), abs(b)

    # Проверка, что b не равно 0
    if b == 0:
        return a  # Si b = 0, le PGCD est a

    # Шаг 1: Инициализация
    g = 1

    # Шаг 2: Убираем общие множители 2
    while is_even(a) and is_even(b):
        a //= 2
        b //= 2
        g *= 2

    # Шаг 3: Основной цикл
    while a != 0:
        # Убираем множители 2 из a
        while is_even(a):
            a //= 2

        # Убираем множители 2 из b
        while is_even(b):
            b //= 2

        # Шаг 4: Вычитание
        if a >= b:
            a = a - b
        else:
            b = b - a

    # Шаг 5: Возвращаем результат
    return g * b


# ===== Тестирование бинарного алгоритма Евклида =====
test_cases = [
    (48, 18),
    (56, 42),
    (101, 10),
    (17, 19),
    (100, 25),
    (81, 27),
    (144, 89),
    (322, 14),
    (0, 5),
    (-48, 18),
    (-56, -42)
]

for a, b in test_cases:
    try:
        gcd_val = binary_euclidean_algorithm(a, b)
        print(f"НОД({a}, {b}) = {gcd_val}")
    except ValueError as e:
        print(f"Ошибка для пары ({a}, {b}): {e}")
print()

# ===== Расширенный алгоритм Евклида =====
def extended_euclidean_algorithm(a: int, b: int) -> tuple[int, int, int]:
    # Проверка, что b не равно 0
    if b == 0:
        raise ValueError("b не должно быть равно 0")

    # Инициализация
    r_prev, r_curr = a, b
    x_prev, x_curr = 1, 0
    y_prev, y_curr = 0, 1

    while r_curr != 0:
        # Целая часть от деления
        quotient = r_prev // r_curr

        # Обновление остатков
        r_next = r_prev - quotient * r_curr
        r_prev, r_curr = r_curr, r_next

        # Обновление коэффициентов Безу
        x_next = x_prev - quotient * x_curr
        y_next = y_prev - quotient * y_curr
        x_prev, x_curr = x_curr, x_next
        y_prev, y_curr = y_curr, y_next

    # Возвращаем НОД и коэффициенты Безу
    return abs(r_prev), x_prev, y_prev


# ===== Тестирование расширенного алгоритма Евклида =====
test_cases = [
    (48, 18),
    (56, 42),
    (101, 10),
    (17, 19),
    (100, 25),
    (81, 27),
    (144, 89),
    (322, 14),
    (-48, 18),
    (-56, -42)
]

for a, b in test_cases:
    try:
        gcd_val, x, y = extended_euclidean_algorithm(a, b)
        print(f"НОД({a}, {b}) = {gcd_val}")
        print(f"Коэффициенты Безу: x = {x}, y = {y}")
        print(f"Проверка: {a} * {x} + {b} * {y} = {a * x + b * y}")
        print()
    except ValueError as e:
        print(f"Ошибка для пары ({a}, {b}): {e}")
        print()