# -*- coding: utf-8 -*-
"""лабм2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11JxXJ25IRvdpR2ZHbPWntJQTHaNtu_ta

Реализация маршрутного шифрования
"""

def columnar_transposition(text: str, password: str) -> str:
    text = text.replace(' ', '').lower()
    password = password.lower()
    n = len(password)
    m = len(text) // n + (1 if len(text) % n != 0 else 0)

    # Remplir le tableau ligne par ligne
    table = [['' for _ in range(n)] for _ in range(m)]
    for i, char in enumerate(text):
        row = i // n
        col = i % n
        table[row][col] = char

    # Trier les colonnes par ordre alphabétique du mot de passe
    sorted_indices = sorted(range(n), key=lambda i: password[i])

    # Lire colonne par colonne dans l'ordre trié
    ciphertext_chars = []
    for col in sorted_indices:
        for row in range(m):
            if table[row][col] != '':
                ciphertext_chars.append(table[row][col])

    return ''.join(ciphertext_chars).upper()


def columnar_decryption(ciphertext: str, password: str) -> str:
    ciphertext = ciphertext.lower()
    password = password.lower()
    n = len(password)
    m = len(ciphertext) // n + (1 if len(ciphertext) % n != 0 else 0)

    # Obtenir l'ordre des colonnes lors du chiffrement
    sorted_indices = sorted(range(n), key=lambda i: password[i])

    # Créer un tableau vide
    table = [['' for _ in range(n)] for _ in range(m)]

    # Calculer le nombre de caractères par colonne
    chars_per_col = [m] * n
    remainder = len(ciphertext) % n
    for i in range(remainder):
        chars_per_col[i] -= 1

    # Remplir le tableau colonne par colonne dans l'ordre trié
    text_idx = 0
    for col_index, original_col in enumerate(sorted_indices):
        col_length = chars_per_col[col_index]
        for row in range(col_length):
            table[row][original_col] = ciphertext[text_idx]
            text_idx += 1

    # Restaurer le texte en lisant ligne par ligne
    plaintext_chars = []
    for row in range(m):
        for col in range(n):
            if table[row][col] != '':
                plaintext_chars.append(table[row][col])

    return ''.join(plaintext_chars)


# ===== Test du chiffrement par transposition =====
text = "нельзя недооценивать противника"
password = "пароль"
print("Texte original:", text)
print("Mot de passe:", password)

encrypted_col = columnar_transposition(text, password)
print("Chiffré:", encrypted_col)

decrypted_col = columnar_decryption(encrypted_col, password)
print("Déchiffré:", decrypted_col)
print()

"""Реализация шифрования с помощью решеток"""

def rot90(matrix, k=1):
    """Rotation de la matrice de 90° k fois."""
    result = matrix.copy()
    for _ in range(k % 4):
        result = [list(reversed(col)) for col in zip(*result)]
    return result


def generate_fleisner_grill(k: int):
    """Génération de la grille de Fleisner."""
    # Créer un carré de base avec des nombres de 1 à k^2
    base = [[(i * k + j + 1) for j in range(k)] for i in range(k)]

    # Créer un grand carré 2k x 2k
    big_square = [[0 for _ in range(2 * k)] for _ in range(2 * k)]

    # Remplir avec les carrés de base tournés
    for i in range(k):
        for j in range(k):
            big_square[i][j] = base[i][j]
            big_square[i][j + k] = rot90(base, 1)[i][j]
            big_square[i + k][j + k] = rot90(base, 2)[i][j]
            big_square[i + k][j] = rot90(base, 3)[i][j]

    return big_square


def fleisner_encrypt(text: str, k: int, password: str) -> str:
    text = text.replace(' ', '').lower()
    password = password.lower()
    required_length = 4 * (k ** 2)

    # Vérification de la longueur du texte
    if len(text) != required_length:
        raise ValueError(f"La longueur du texte doit être {required_length}, reçu {len(text)}")

    # Génération de la grille
    grill = generate_fleisner_grill(k)

    # Créer une table pour l'écriture
    table = [['' for _ in range(2 * k)] for _ in range(2 * k)]
    text_chars = list(text)
    text_index = 0

    # Écriture avec rotation de la grille (4 rotations)
    for rotation in range(4):
        rotated_grill = rot90(grill, rotation)

        # Recherche des cellules pour l'écriture (valeurs de 1 à k^2)
        for i in range(2 * k):
            for j in range(2 * k):
                if 1 <= rotated_grill[i][j] <= k ** 2:
                    if text_index < len(text_chars):
                        table[i][j] = text_chars[text_index]
                        text_index += 1

    # Trier les colonnes par ordre alphabétique des lettres du mot de passe
    # Répéter le mot de passe pour couvrir toutes les colonnes
    extended_password = (password * (2 * k))[:2 * k]
    sorted_indices = sorted(range(2 * k), key=lambda i: extended_password[i])

    ciphertext_chars = []
    for col in sorted_indices:
        for i in range(2 * k):
            if table[i][col] != '':  # Éviter les cellules vides
                ciphertext_chars.append(table[i][col])

    return ''.join(ciphertext_chars).upper()


# ===== Test du chiffrement par grilles =====
k = 2
grill_text = "договор подписан"
grill_text_clean = grill_text.replace(' ', '').lower()

# Vérification de la longueur
required_length = 4 * (k ** 2)
if len(grill_text_clean) != required_length:
    print(f"Complétion du texte à {required_length} caractères")
    if len(grill_text_clean) < required_length:
        grill_text_clean += 'x' * (required_length - len(grill_text_clean))
    else:
        grill_text_clean = grill_text_clean[:required_length]

grill_password = "шифр"
print("Texte original:", grill_text)
print("Texte préparé:", grill_text_clean)
print("Longueur du texte:", len(grill_text_clean))
print("k:", k)
print("Mot de passe:", grill_password)

encrypted_grill = fleisner_encrypt(grill_text_clean, k, grill_password)
print("Chiffré:", encrypted_grill)
print()

""" Реализация таблицы Виженера"""

def vigenere_cipher(text: str, key: str) -> str:
    text = text.replace(' ', '').lower()
    key = key.lower()
    alphabet = list("абвгдеёжзийклмнопрстуфхцчшщъыьэюя")
    n = len(alphabet)

    # Étendre la clé à la longueur du texte
    extended_key = []
    key_chars = list(key)
    for i in range(len(text)):
        extended_key.append(key_chars[i % len(key)])

    ciphertext_chars = []
    for i, char in enumerate(text):
        if char in alphabet:
            char_idx = alphabet.index(char)
            key_char = extended_key[i]
            key_idx = alphabet.index(key_char)
            new_idx = (char_idx + key_idx) % n
            ciphertext_chars.append(alphabet[new_idx])
        else:
            ciphertext_chars.append(char)

    return ''.join(ciphertext_chars).upper()


def vigenere_decipher(ciphertext: str, key: str) -> str:
    ciphertext = ciphertext.lower()
    key = key.lower()
    alphabet = list("абвгдеёжзийклмнопрстуфхцчшщъыьэюя")
    n = len(alphabet)

    # Étendre la clé à la longueur du texte chiffré
    extended_key = []
    key_chars = list(key)
    for i in range(len(ciphertext)):
        extended_key.append(key_chars[i % len(key)])

    plaintext_chars = []
    for i, char in enumerate(ciphertext):
        if char in alphabet:
            char_idx = alphabet.index(char)
            key_char = extended_key[i]
            key_idx = alphabet.index(key_char)
            new_idx = (char_idx - key_idx + n) % n
            plaintext_chars.append(alphabet[new_idx])
        else:
            plaintext_chars.append(char)

    return ''.join(plaintext_chars)


# ===== Test du chiffre de Vigenère =====
vigenere_text = "криптография серьезная наука"
vigenere_key = "математика"
print("Texte original:", vigenere_text)
print("Clé:", vigenere_key)

# Chiffrement
encrypted = vigenere_cipher(vigenere_text, vigenere_key)
print("Texte chiffré:", encrypted)

# Déchiffrement
decrypted = vigenere_decipher(encrypted, vigenere_key)
print("Texte déchiffré:", decrypted)

# Vérification
print("\nVérification:")
print(f"Le texte déchiffré correspond à l'original (sans espaces) : {decrypted == vigenere_text.replace(' ', '').lower()}")