# -*- coding: utf-8 -*-
"""лабм5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNjSyzcQrhZN5e1qPDbqrjfkXf75xWVZ
"""

import random
from math import gcd

# ===== Реализация вычисления символа Якоби =====
def jacobi_symbol(a: int, n: int) -> int:
    """
    Вычисление символа Якоби (a/n) для нечетного n >= 3.
    """
    # Проверка на простые случаи
    if n % 2 == 0 or n < 3:
        raise ValueError("n должно быть нечетным и >= 3")

    # Приведение a по модулю n
    a = a % n

    # Инициализация
    g = 1
    a_current = a
    n_current = n

    while True:
        # Шаг 2: если a_current == 0, возвращаем 0
        if a_current == 0:
            return 0

        # Шаг 3: если a_current == 1, возвращаем g
        if a_current == 1:
            return g

        # Шаг 4: Выделение степеней двойки из a_current
        k = 0
        a_temp = a_current
        while a_temp % 2 == 0:
            k += 1
            a_temp //= 2
        a1 = a_temp

        # Шаг 5: вычисление s на основе k и n_current
        if k % 2 == 0:
            s = 1
        else:
            n_mod8 = n_current % 8
            if n_mod8 == 1 or n_mod8 == 7:
                s = 1
            else:
                s = -1

        # Шаг 6: если a1 == 1, возвращаем g * s
        if a1 == 1:
            return g * s

        # Шаг 7: проверка условия для изменения s
        if n_current % 4 == 3 and a1 % 4 == 3:
            s = -s

        # Шаг 8: обновление переменных для следующей операции
        a_current = n_current % a1
        n_current = a1
        g = g * s


# ===== Тест Ферма =====
def fermat_test(n: int, trials: int = 1) -> str:
    """
    Вероятностный тест простоты Ферма.
    """
    # Проверка входных данных
    if n < 5:
        raise ValueError("n должно быть >= 5")
    if n % 2 == 0:
        return f"Число {n} составное"

    for _ in range(trials):
        # Шаг 1: Выбор случайного основания a
        a = random.randint(2, n - 2)

        # Шаг 2: Вычисление a^(n-1) mod n
        r = pow(a, n - 1, n)

        # Шаг 3: проверка условия
        if r != 1:
            return f"Число {n} составное"
    return f"Число {n}, вероятно, простое"


# ===== Тест Соловея-Штрассена =====
def solovay_strassen_test(n: int, trials: int = 1) -> str:
    """
    Вероятностный тест простоты Соловея-Штрассена.
    """
    # Проверка входных данных
    if n < 5:
        raise ValueError("n должно быть >= 5")
    if n % 2 == 0:
        return f"Число {n} составное"

    for _ in range(trials):
        # Шаг 1: Выбор случайного основания a
        a = random.randint(2, n - 2)

        # Проверка НОД(a, n)
        if gcd(a, n) > 1:
            return f"Число {n} составное"

        # Шаг 2: Вычисление a^((n-1)/2) mod n
        r = pow(a, (n - 1) // 2, n)

        # Шаг 3: проверка значений
        if r != 1 and r != n - 1:
            return f"Число {n} составное"

        # Шаг 4: Вычисление символа Якоби
        j = jacobi_symbol(a, n)

        # Шаг 5: проверка соответствия
        if (r == n - 1) and (j == -1):
            continue
        elif r == 1 and j == 1:
            continue
        else:
            return f"Число {n} составное"
    return f"Число {n}, вероятно, простое"


# ===== Тест Миллера-Рабина =====
def miller_rabin_test(n: int, trials: int = 1) -> str:
    """
    Вероятностный тест простоты Миллера-Рабина.
    """
    # Проверка входных данных
    if n < 5:
        raise ValueError("n должно быть >= 5")
    if n % 2 == 0:
        return f"Число {n} составное"

    # Шаг 1: представление n-1 в виде 2^s * d
    s = 0
    d = n - 1
    while d % 2 == 0:
        s += 1
        d //= 2

    for _ in range(trials):
        # Шаг 2: выбор случайного основания a
        a = random.randint(2, n - 2)

        # Шаг 3: вычисление y = a^d mod n
        y = pow(a, d, n)

        # Шаг 4: проверка условия
        if y != 1 and y != n - 1:
            j = 1
            while j <= s - 1 and y != n - 1:
                # Шаг 4.2.1: возведение в квадрат по модулю
                y = pow(y, 2, n)

                # Шаг 4.2.2: проверка на нетривиальный корень
                if y == 1:
                    return f"Число {n} составное"
                j += 1
            # Шаг 4.3: окончательная проверка
            if y != n - 1:
                return f"Число {n} составное"
    return f"Число {n}, вероятно, простое"


# ===== Проверка чисел на простоту =====
if __name__ == "__main__":
    n = 101
    a = 7

    print(f"Тест Ферма: {fermat_test(n, 5)}")
    print(f"Тест Соловея-Штрассена: {solovay_strassen_test(n, 5)}")
    print(f"Тест Миллера-Рабина: {miller_rabin_test(n, 5)}")
    print(f"\nСимвол Якоби для a={a} и n={n}: {jacobi_symbol(a, n)}")