# -*- coding: utf-8 -*-
"""лабм1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rJnz-DtKuaw_NgHOhvB2cRLpJMQsEah

Шифр Цезаря с произвольным ключом K
"""

def caesar_cipher(text: str, k: int) -> str:
    """
    Шифр Цезаря с произвольным ключом K
    """
    # Создание массива символов русского алфавита (без ё)
    alphabet = list("абвгдежзийклмнопрстуфхцчшщъыьэюя")

    # Инициализация пустой строки для результата
    result = ""

    # Итерация по каждому символу в тексте, приведенному к нижнему регистру
    for char in text.lower():
        # Поиск индекса символа в алфавите
        try:
            idx = alphabet.index(char)
            # Вычисление индекса символа с учетом ключа k и цикличности алфавита
            new_idx = (idx + k) % len(alphabet)
            # Добавление зашифрованного символа к результату
            result += alphabet[new_idx]
        except ValueError:
            # Если символ не из алфавита (пробел, знак препинания), добавляем без изменений
            result += char

    # Возврат полученной зашифрованной строки
    return result


# ===== Тестирование шифра Цезаря =====
#print("Тестирование шифра Цезаря:")
#print(caesar_cipher("студент", 4))  # Должно вывести: хцчийсц
#fprint()
print( "Тестирование шифра Цезаря:")
print(caesar_cipher("студент", 4))

""" Шифр Атбаш

"""

def atbash_cipher(text: str) -> str:
    """
    Шифр Атбаш - зеркальное отображение алфавита
    """
    # Создание массива символов русского алфавита (без ё)
    alphabet = list("абвгдежзийклмнопрстуфхцчшщъыьэюя")

    # Инициализация пустой строки для результата
    result = ""

    # Итерация по каждому символу в тексте в нижнем регистре
    for char in text.lower():
        # Поиск индекса символа в алфавите
        try:
            idx = alphabet.index(char)
            # Вычисление индекса симметричного символа (от конца алфавита)
            result += alphabet[len(alphabet) - idx - 1]
        except ValueError:
            # Если символ не из алфавита, добавляем без изменений
            result += char

    # Возврат результата
    return result


# ===== Тестирование шифра Атбаш =====
print("Тестирование шифра Атбаш:")
print(atbash_cipher("студент"))  # Должно вывести: онмыътн
print()